Add customizable section header
dangoslen/dependabot-changelog-helper pull request #201
Opened 2023-11-07 21:59 UTC by ChristopherBeltran

Addresses https://github.com/dangoslen/dependabot-changelog-helper/issues/200.

2023-11-08 03:01 UTC, dangoslen requested changes
Overall this looks good! TY for the docs and tests.

I think we can do some better defaulting via the GitHub action file and that way better enforce someone attempting to set a blank section header value

2023-11-08 15:23 UTC, ChristopherBeltran commented on __tests__/changelog-updater.test.ts
> +  await updateChangelog(PACKAGE_ENTRY, 'UNRELEASED', './CHANGELOG.md', 'Bump', '')
Makes sense, forgot about the `action.yml` file 😅 .  Removed this.

2023-11-08 15:24 UTC, ChristopherBeltran commented on src/changelog-updater.ts
> +      sectionHeader || 'Dependencies'
Yep I agree, removed the default fallback.

2023-11-08 15:24 UTC, ChristopherBeltran commented on src/changelog-updater.ts
> +    `^### (${sectionHeader}|Dependencies|DEPENDENCIES)`
Much cleaner 👍 Updated.

2023-11-09 00:08 UTC, dangoslen approved these changes
Looks great! I'll get this merged in and cut in a `3.6.0` release soon

2023-11-09 00:08 UTC, dangoslen commented on action.yml
> +  sectionHeader:
👏🏼

2023-11-09 00:10 UTC, merged